### ISSUE TITLE
Scaffolding Project

### ISSUE THREAD

**Issue by blarzHernandez** [chingu-coders/Voyage2-Turtles-04#4]
Scaffolding of the project
- [x] Set Up - Bootstrapping (@abuna1985)
 - [x] Setup of File / DB / URL - Where are we going to get the images and prices. (@abuna1985,blarzHernandez)
- [x] Setup app on heroku (@blarzHernandez)

**Comment by abuna1985** [comment]
Completed set-up. We are going to have to use webpack as a workaround for using bootstrap in react. There are a few react-bootstrap files. We can also use the BEM method with Sass. But the set-up is good for now.

**Comment by blarzHernandez** [comment]
We are going to use Flickr API.
https://www.flickr.com/services/api/
